# Generated by Django 6.0.5 on 2026-07-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='location',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='service_requests/'),
        ),
    ]
