# Generated by Django 6.0.7 on 2026-07-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_servicerequest_latitude_servicerequest_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='rating',
            new_name='mechanic_rating',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='customer_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
